<<<<<<< HEAD
# ================================
# AWS Configuration
# ================================
aws_region=ap-south-1
ami_id=ami-01a00762f46d584a1
instance_type=t3.micro
key_name=my-key


# ================================
# Docker Configuration
# ================================
=======
# ==========================================
# AWS CONFIGURATION
# ==========================================

aws_region=ap-south-1

>>>>>>> 8f4d280e79b0890f7d9a17b4e1d485fb8a747beb
docker_username=saurabhs2002

frontend_image=todo-frontend
backend_image=todo-backend


<<<<<<< HEAD
# ================================
# Application Directories
# ================================
terraform_directory=terraform-demo

frontend_directory=frontend

backend_directory=backend


# ================================
# Monitoring Configuration
# ================================
prometheus_directory=monitoring/prometheus


# ================================
# EC2 Configuration
# ================================
ec2_user=ubuntu
=======
# ==========================================
# EC2 CONFIGURATION
# ==========================================

ec2_user=ubuntu

ami_id=ami-01a00762f46d584a1

instance_type=t3.micro

# AWS EC2 Key Pair NAME
key_value=my-ec2-key


# ==========================================
# DIRECTORY CONFIGURATION
# ==========================================

terraform_directory=terraform-demo

frontend_directory=frontend

backend_directory=backend
>>>>>>> 8f4d280e79b0890f7d9a17b4e1d485fb8a747beb
