####
AWS_REGION=ap-south-1

DOCKER_USERNAME=saurabhs2002

EC2_USER=ubuntu

TERRAFORM_DIR=terraform-demo

FRONTEND_DIR=frontend

BACKEND_DIR=backend

FRONTEND_REPOSITORY=frontend

BACKEND_REPOSITORY=backend
