aws_region=ap-south-1

docker_username=saurabhs2002

ec2_user=ubuntu

terraform_directory=terraform-demo

frontend_directory=frontend

backend_directory=backend

frontend_image=saurabhs2002/frontend

backend_image=saurabhs2002/backend

ami_id=ami-01a00762f46d584a1

instance_type=t3.micro

key_value=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPfxBx9PMxz4I5U7k1e7y9qgWGUsTZVSLf0XML6S5pOd ubuntu@ip-172-31-36-217
